# Generated by Django 4.0.1 on 2022-01-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='viewer',
        ),
    ]
